name: "OpenAPI Analyzer"
description: "Analyze OpenAPI documentation and suggest best practices"
author: "ApyGuard"
inputs:
  spec_url:
    description: "URL to the OpenAPI spec"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
