name: Test OpenAPI Analyzer
on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run analyzer from local repo
        uses: ./   # <-- important: runs your local Action, not marketplace version
        with:
          spec_url: "https://petstore3.swagger.io/api/v3/openapi.json"